name: Publish

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish

    steps:
      - uses: actions/checkout@master
      - run: npm i
      - run: npm version ${{ github.event.release.tag_name }} --git-tag-version=false
      - run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
